// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Tdemy3au2lN1jpBl0qeHgEYDh9mYpmk',
    appId: '1:749031033893:web:be0df85fb0d94f1f8843cc',
    messagingSenderId: '749031033893',
    projectId: 'doctors-appointments-11baa',
    authDomain: 'doctors-appointments-11baa.firebaseapp.com',
    storageBucket: 'doctors-appointments-11baa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqiqsOaoazEeSPpGzAJSAoq_v_HJ0jQgQ',
    appId: '1:749031033893:android:30dfe0b13cb4942b8843cc',
    messagingSenderId: '749031033893',
    projectId: 'doctors-appointments-11baa',
    storageBucket: 'doctors-appointments-11baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0DG8gEkfpv1TRJeFb1jzyuy2wzGAB7M',
    appId: '1:749031033893:ios:b4a54e8aa92ebf208843cc',
    messagingSenderId: '749031033893',
    projectId: 'doctors-appointments-11baa',
    storageBucket: 'doctors-appointments-11baa.appspot.com',
    iosClientId: '749031033893-u3a1eo42ptpnpi151jjpp77hghrrrhjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsAppointments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0DG8gEkfpv1TRJeFb1jzyuy2wzGAB7M',
    appId: '1:749031033893:ios:b4a54e8aa92ebf208843cc',
    messagingSenderId: '749031033893',
    projectId: 'doctors-appointments-11baa',
    storageBucket: 'doctors-appointments-11baa.appspot.com',
    iosClientId: '749031033893-u3a1eo42ptpnpi151jjpp77hghrrrhjq.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorsAppointments',
  );
}
